# Generated by Django 5.0.4 on 2024-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=30)),
                ('station_name', models.CharField(max_length=30)),
                ('rackTotCnt', models.IntegerField()),
                ('parkingBikeTotCnt', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
