# Generated by Django 5.0.4 on 2024-04-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='station_id',
            new_name='stationId',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='latitude',
            new_name='stationLatitude',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='station_name',
            new_name='stationName',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='longitude',
            new_name='stationlongitude',
        ),
    ]
