# Generated by Django 5.0.4 on 2024-04-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_station_id_station_stationid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='stationlongitude',
            new_name='stationLongitude',
        ),
    ]
