# Generated by Django 5.0.4 on 2024-04-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='dong',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='station',
            name='gu',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
