# Generated by Django 5.0.4 on 2024-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollenAddrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_code', models.CharField(max_length=10, verbose_name='행정구역코드')),
                ('addr1', models.CharField(max_length=20, verbose_name='행정주소1(시)')),
                ('addr2', models.CharField(max_length=20, verbose_name='행정주소2(구)')),
                ('addr3', models.CharField(max_length=20, verbose_name='행정주소3(동)')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PollenApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twodaysaftertomorrow', models.IntegerField()),
            ],
        ),
    ]
