# Generated by Django 5.0.4 on 2024-04-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulBikeStationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='대여소 ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='대여소 이름')),
                ('raccnt', models.ImageField(upload_to='', verbose_name='거치대 수')),
                ('addr1', models.CharField(max_length=20, verbose_name='구')),
                ('addr2', models.CharField(max_length=20, verbose_name='동')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SeoulBikeStationNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikecnt', models.IntegerField(verbose_name='자전거 수')),
                ('bikeratio', models.IntegerField(verbose_name='거치율')),
            ],
        ),
    ]
