# Generated by Django 5.0.4 on 2024-04-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoulbike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoulbikestationnow',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='now', to='seoulbike.seoulbikestationinfo'),
        ),
        migrations.AlterField(
            model_name='seoulbikestationinfo',
            name='raccnt',
            field=models.IntegerField(verbose_name='거치대 수'),
        ),
        migrations.AlterField(
            model_name='seoulbikestationnow',
            name='bikecnt',
            field=models.IntegerField(default=0, verbose_name='자전거 수'),
        ),
    ]
