# Generated by Django 5.0.4 on 2024-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoulbike', '0002_seoulbikestationnow_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoulbikestationinfo',
            name='station_id',
            field=models.CharField(max_length=20, verbose_name='대여소 ID'),
        ),
    ]
